SUPPORTED_LANGUAGES = ["en", "ru", "de"]
_locales = {
    "en": {
        "menu_title": "ObfUtil version {VERSION}",
        "menu_description": "Advanced encryption tool",
        "cfg_file_cfg": "Config File",
        "key_file_cfg": "Key File",
        "key_path_cfg": "Key path",
        "version_title": "Version",
        "usage": "USAGE:",
        "commands": "COMMANDS:",
        "options": "OPTIONS:",
        "examples": "EXAMPLES:",
        "encrypt_cmd": "Encrypt file",
        "decrypt_cmd": "Decrypt and edit file",
        "view_cmd": "View content",
        "vault_cmd": "Manage encrypted vaults",
        "help_opt": "Show help",
        "lang_opt": "Language (en/ru)",
        "encrypt_example": "Encryption: obfUtil encrypt file.ext",
        "decrypt_example": "Decryption: obfUtil decrypt file.ext.enc",
        "view_example": "View: obfUtil view file.ext.enc",
        "vault_example": "Vault: obfUtil vault create name --size MB --password",
        "password_prompt": "Enter password: ",
        "file_encrypted": "File encrypted: {}",
        "edit_file": "Editing file: {}",
        "press_enter": "Press Enter after editing to re-encrypt...",
        "file_reencrypted": "File re-encrypted successfully!",
        "encrypt_error": "Encryption error: {}",
        "decrypt_error": "Decryption error: {}",
        "gen_key": "Generate new key (for --key-file encryption)",
        "gen_key_created": "Key file successfully created: ",
        "lang_opt_desc": "Change interface language (en/ru/de)",
        "key_file_enc": "Use key file encryption",
        "use_pass_enc": "Use password encryption",
        "gen_pass": "Generate password ( >8 symbols )",
        "generated_pass": "Generated password:",
        "obfuscate_cmd": "Obfuscate Python script",
        "file_obfuscated": "File successfully obfuscated:",
        "error": "Error: {}",
        "invalid_cmd": "Invalid command: {}",
        "file_encrypted_with_integrity": "File encrypted with integrity protection: {}",
        "integrity_check_failed": "INTEGRITY CHECK FAILED: {}",
        "file_tampered": "File has been modified or corrupted!",
        "integrity_verified": "File integrity verified successfully",
        "encrypt_int_cmd": "Encrypt with integrity check",
        "verify_int_cmd": "Verify integrity of file",
        "show_examples_cmd": "Show all usage examples",
        "examples_title": "USAGE EXAMPLES",
        "password_generation": "PASSWORD GENERATION:",
        "key_management": "KEY MANAGEMENT:",
        "obfuscation": "CODE OBFUSCATION:",
        "encryption_password": "ENCRYPTION (PASSWORD):",
        "encryption_keyfile": "ENCRYPTION (KEY FILE):",
        "integrity_operations": "INTEGRITY OPERATIONS:",
        "vault_operations": "VAULT OPERATIONS:",
        "decryption_viewing": "DECRYPTION & VIEWING:",
        "language_settings": "LANGUAGE SETTINGS:",
        "workflow_examples": "WORKFLOW EXAMPLES:",
        "gen_pass_12": "Generate 12-character password",
        "gen_key_example": "Generate encryption key file",
        "obfuscate_simple": "Obfuscate Python script",
        "encrypt_pass_file": "Encrypt file with password",
        "encrypt_key_file": "Encrypt file with key file",
        "encrypt_integrity_pass": "Encrypt with integrity check (password)",
        "encrypt_integrity_key": "Encrypt with integrity check (key file)",
        "verify_integrity_pass": "Verify file integrity (password)",
        "vault_create_pass": "Create 100MB vault with password",
        "vault_create_key": "Create 500MB vault with key file",
        "vault_list": "List all vaults",
        "vault_info": "Show vault information",
        "vault_add_file": "Add file to vault",
        "vault_list_files": "List files in vault",
        "vault_extract_file": "Extract file from vault",
        "vault_remove_file": "Remove file from vault",
        "vault_delete": "Delete vault",
        "vault_move_file": "Move file to vault (delete original)",
        "decrypt_edit_pass": "Decrypt and edit file (password)",
        "view_only_key": "View file content only (key file)",
        "decrypt_integrity_pass": "Decrypt with integrity check (password)",
        "change_lang": "Change interface language",
        "workflow_1": "Obfuscation + Encryption:",
        "workflow_2": "Secure workflow with integrity:",
        "workflow_3": "Password-based workflow:",
        "workflow_4": "Vault management workflow:",
        "vault_created": "Vault created successfully: {}",
        "vault_deleted": "Vault deleted successfully: {}",
        "vault_not_found": "Vault not found: {}",
        "vault_exists": "Vault already exists: {}",
        "vault_list_empty": "No vaults found",
        "vault_size_invalid": "Vault size must be between 1MB and 1024MB",
        "vault_help_title": "ObfUtil Vault - Encrypted File Containers",
        "vault_help_usage": "Usage: obfutil vault <command> [options]",
        "vault_help_examples": "EXAMPLES:",

        # New commands (V3.1)
        "status_cmd": "Show system status and health",
        "config_cmd": "Manage system configuration",
        
        # New examples (V3.1)
        "status_example": "Show system status and statistics",
        "config_example": "Show config",
        "config_show_example": "Show current configuration",
        "batch_encrypt_example": "Encrypt all .txt files in current directory",
        "batch_decrypt_example": "Decrypt all .enc files in current directory",
        
        # New categories (V3.1)
        "system_operations": "SYSTEM OPERATIONS:",
        "batch_operations": "BATCH OPERATIONS:",
        
        # Status messages
        "system_status": "System Status",
        "vaults_count": "Vaults count",
        "key_file_status": "Key file status",
        "logs_size": "Logs size",
        "configuration": "Configuration",
        "current_language": "Current language",
        "encryption_method": "Encryption method",
        'system_status': 'SYSTEM STATUS',

        "batch_stats_files": "Files processed",
        "batch_stats_successful": "Successful", 
        "batch_stats_failed": "Failed",
        "batch_stats_total_size": "Total size",
        "batch_stats_processed_size": "Processed size",
        "batch_stats_processing_time": "Processing time",
        "batch_stats_speed": "Average speed",
        "key_size": "Key size",
        "logs_dir": "Logs directory",
        "vaults_dir": "Vaults directory",
        "exists": "Exists",
        "not_found": "Not found",
        "seconds": "seconds",

        "vault_analyze": "Analyze vault usage",
        "vault_capacity": "Capacity",
        "vault_used_space": "Used space",
        "vault_free_space": "Free space", 
        "vault_largest_file": "Largest file",
        "vault_file_types": "File types",
        "total_files": "Total files",
        "total_size": "Total size",
    },
    "ru": {
        "menu_title": "ObfUtil версия {VERSION}",
        "menu_description": "Продвинутый инструмент шифрования",
        "cfg_file_cfg": "Файл конфига",
        "key_file_cfg": "Ключ",
        "key_path_cfg": "Путь к ключу",
        "version_title": "Версия",
        "usage": "ИСПОЛЬЗОВАНИЕ:",
        "commands": "КОМАНДЫ:",
        "options": "ОПЦИИ:",
        "examples": "ПРИМЕРЫ:",
        "encrypt_cmd": "Зашифровать файл",
        "decrypt_cmd": "Расшифровать и отредактировать файл",
        "view_cmd": "Просмотр содержимого",
        "vault_cmd": "Управление зашифрованными сейфами",
        "help_opt": "Показать помощь",
        "lang_opt": "Язык (en/ru)",
        "encrypt_example": "Шифрование: obfUtil encrypt file.ext.py",
        "decrypt_example": "Дешифрование: obfUtil decrypt file.ext.enc",
        "view_example": "Просмотр: obfUtil view file.ext.enc",
        "vault_example": "Сейф: obfUtil vault create имя --size МБ --password",
        "password_prompt": "Введите пароль: ",
        "file_encrypted": "Файл зашифрован:",
        "edit_file": "Редактирование файла:",
        "press_enter": "Нажмите Enter после редактирования для повторного шифрования...",
        "file_reencrypted": "Файл успешно повторно зашифрован!",
        "encrypt_error": "Ошибка шифрования: {}",
        "decrypt_error": "Ошибка расшифровки: {}",
        "gen_key": "Создать новый ключ (для шифрования с --key-file)",
        "gen_key_created": "Ключ успешно создан: ",
        "lang_opt_desc": "Сменить язык интерфейса (en/ru/de)",
        "key_file_enc": "Использовать шифрование файлом ключа",
        "use_pass_enc": "Использовать шифрование паролем",
        "gen_pass": "Сгенерировать пароль ( >8 символов )",
        "generated_pass": "Сгенерированный пароль:",
        "obfuscate_cmd": "Обфусцировать Python скрипт",
        "file_obfuscated": "Файл успешно обфусцирован:",
        "error": "Ошибка: {}",
        "invalid_cmd": "Неверная команда: {}",
        "file_encrypted_with_integrity": "Файл зашифрован с проверкой целостности: {}",
        "integrity_check_failed": "ПРОВЕРКА ЦЕЛОСТНОСТИ ПРОВАЛИЛАСЬ: {}",
        "file_tampered": "Файл изменен или сломан!",
        "integrity_verified": "Проверка целостности прошла успешно",
        "encrypt_int_cmd": "Зашифровать с проверкой целостности",
        "verify_int_cmd": "Проверить целостность файла",
        "show_examples_cmd": "Показать все примеры использования",
        "examples_title": "ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ",
        "password_generation": "ГЕНЕРАЦИЯ ПАРОЛЕЙ:",
        "key_management": "УПРАВЛЕНИЕ КЛЮЧАМИ:",
        "obfuscation": "ОБФУСЦИРОВАНИЕ КОДА:",
        "encryption_password": "ШИФРОВАНИЕ (ПАРОЛЬ):",
        "encryption_keyfile": "ШИФРОВАНИЕ (ФАЙЛ КЛЮЧА):",
        "integrity_operations": "ОПЕРАЦИИ ЦЕЛОСТНОСТИ:",
        "vault_operations": "ОПЕРАЦИИ С СЕЙФАМИ:",
        "decryption_viewing": "ДЕШИФРОВАНИЕ И ПРОСМОТР:",
        "language_settings": "НАСТРОЙКИ ЯЗЫКА:",
        "workflow_examples": "ПРИМЕРЫ РАБОЧИХ ПРОЦЕССОВ:",
        "gen_pass_12": "Сгенерировать пароль из 12 символов",
        "gen_key_example": "Сгенерировать файл ключа шифрования",
        "obfuscate_simple": "Обфусцировать Python скрипт",
        "encrypt_pass_file": "Зашифровать файл с паролем",
        "encrypt_key_file": "Зашифровать файл с файлом ключа",
        "encrypt_integrity_pass": "Зашифровать с проверкой целостности (пароль)",
        "encrypt_integrity_key": "Зашифровать с проверкой целостности (файл ключа)",
        "verify_integrity_pass": "Проверить целостность файла (пароль)",
        "vault_create_pass": "Создать сейф 100MB с паролем",
        "vault_create_key": "Создать сейф 500MB с файлом ключа",
        "vault_list": "Показать все сейфы",
        "vault_info": "Показать информацию о сейфе",
        "vault_add_file": "Добавить файл в сейф",
        "vault_list_files": "Показать файлы в сейфе",
        "vault_extract_file": "Извлечь файл из сейфа",
        "vault_remove_file": "Удалить файл из сейфа",
        "vault_delete": "Удалить сейф",
        "vault_move_file": "Переместить файл в сейф (удалить оригинал)",
        "decrypt_edit_pass": "Расшифровать и редактировать файл (пароль)",
        "view_only_key": "Только просмотреть содержимое (файл ключа)",
        "decrypt_integrity_pass": "Расшифровать с проверкой целостности (пароль)",
        "change_lang": "Сменить язык интерфейса",
        "workflow_1": "Обфускация + Шифрование:",
        "workflow_2": "Безопасный процесс с проверкой целостности:",
        "workflow_3": "Процесс на основе пароля:",
        "workflow_4": "Процесс управления сейфами:",
        "vault_created": "Сейф успешно создан: {}",
        "vault_deleted": "Сейф успешно удален: {}",
        "vault_not_found": "Сейф не найден: {}",
        "vault_exists": "Сейф уже существует: {}",
        "vault_list_empty": "Сейфы не найдены",
        "vault_size_invalid": "Размер сейфа должен быть от 1MB до 1024MB",
        "vault_help_title": "ObfUtil Vault - Зашифрованные файловые контейнеры",
        "vault_help_usage": "Использование: obfutil vault <команда> [опции]",
        "vault_help_examples": "ПРИМЕРЫ:",

        "status_cmd": " Показать статус системы",
        "config_cmd": " Управление настройками системы",
        
        "status_example": "Показать статус системы и статистику",
        "config_example": "Сменить язык системы на русский",
        "config_show_example": "Показать текущие настройки",
        "batch_encrypt_example": "Зашифровать все .txt файлы в текущей директории",
        "batch_decrypt_example": "Расшифровать все .enc файлы в текущей директории",
        
        "system_operations": "СИСТЕМНЫЕ ОПЕРАЦИИ:",
        "batch_operations": "МАССОВЫЕ ОПЕРАЦИИ:",
        
        "system_status": "Статус системы",
        "vaults_count": "Количество сейфов",
        "key_file_status": "Статус ключевого файла",
        "logs_size": "Размер логов",
        "configuration": "Конфигурация",
        "current_language": "Текущий язык",
        "encryption_method": "Метод шифрования",
        'system_status': 'СТАТУС СИСТЕМЫ',

        "batch_stats_files": "Файлов обработано",
        "batch_stats_successful": "Успешно",
        "batch_stats_failed": "Неудачно", 
        "batch_stats_total_size": "Общий размер",
        "batch_stats_processed_size": "Обработанный размер",
        "batch_stats_processing_time": "Время обработки",
        "batch_stats_speed": "Средняя скорость",
        "key_size": "Размер ключа",
        "logs_dir": "Директория логов",
        "vaults_dir": "Директория сейфов",
        "exists": "Существует",
        "not_found": "Не найдено",
        "seconds": "секунд",

        "vault_analyze": "Анализ использования сейфа",
        "vault_capacity": "Вместимость",
        "vault_used_space": "Занято места",
        "vault_free_space": "Свободно места",
        "vault_largest_file": "Самый большой файл",
        "vault_file_types": "Типы файлов",
        "total_files": "Всего файлов",
        "total_size": "Общий размер",
    },
    "de": {
        "menu_title": "ObfUtil Version {VERSION}",
        "menu_description": "Erweitertes Verschlüsselungstool",
        "cfg_file_cfg": "Datei Konfigurieren",
        "key_file_cfg": "Schlüsseldatei",
        "key_path_cfg": "Schlüsselpfad",
        "version_title": "Version",
        "usage": "VERWENDUNG:",
        "commands": "BEFEHLE:",
        "options": "OPTIONEN:",
        "examples": "BEISPIELE:",
        "encrypt_cmd": "Datei verschlüsseln",
        "decrypt_cmd": "Datei entschlüsseln und bearbeiten",
        "view_cmd": "Inhalt anzeigen",
        "vault_cmd": "Verwaltung verschlüsselter Tresore",
        "help_opt": "Hilfe anzeigen",
        "lang_opt": "Sprache (en/ru/de)",
        "encrypt_example": "Verschlüsselung: obfUtil encrypt datei.ext",
        "decrypt_example": "Entschlüsselung: obfUtil decrypt datei.ext.enc",
        "view_example": "Anzeigen: obfUtil view datei.ext.enc",
        "vault_example": "Tresor: obfUtil vault create name --size MB --password",
        "password_prompt": "Passwort eingeben: ",
        "file_encrypted": "Datei verschlüsselt: {}",
        "edit_file": "Datei bearbeiten: {}",
        "press_enter": "Drücken Sie Enter nach der Bearbeitung zum erneuten Verschlüsseln...",
        "file_reencrypted": "Datei erfolgreich neu verschlüsselt!",
        "encrypt_error": "Verschlüsselungsfehler: {}",
        "decrypt_error": "Entschlüsselungsfehler: {}",
        "gen_key": "Neuen Schlüssel generieren (für --key-file Verschlüsselung)",
        "gen_key_created": "Schlüsseldatei erfolgreich erstellt: ",
        "lang_opt_desc": "Oberflächensprache ändern (en/ru/de)",
        "key_file_enc": "Schlüsseldatei-Verschlüsselung verwenden",
        "use_pass_enc": "Passwort-Verschlüsselung verwenden",
        "gen_pass": "Passwort generieren ( >8 Zeichen )",
        "generated_pass": "Generiertes Passwort:",
        "obfuscate_cmd": "Python-Script obfuszieren",
        "file_obfuscated": "Datei erfolgreich obfusziert:",
        "error": "Fehler: {}",
        "invalid_cmd": "Ungültiger Befehl: {}",
        "file_encrypted_with_integrity": "Datei mit Integritätsschutz verschlüsselt: {}",
        "integrity_check_failed": "INTEGRITÄTSÜBERPRÜFUNG FEHLGESCHLAGEN: {}",
        "file_tampered": "Datei wurde verändert oder beschädigt!",
        "integrity_verified": "Dateiintegrität erfolgreich überprüft",
        "encrypt_int_cmd": "Mit Integritätsprüfung verschlüsseln",
        "verify_int_cmd": "Dateiintegrität überprüfen",
        "show_examples_cmd": "Alle Verwendungsbeispiele anzeigen",
        "examples_title": "VERWENDUNGSBEISPIELE",
        "password_generation": "PASSWORTGENERIERUNG:",
        "key_management": "SCHLÜSSELVERWALTUNG:",
        "obfuscation": "CODE-OBFUSZIERUNG:",
        "encryption_password": "VERSCHLÜSSELUNG (PASSWORT):",
        "encryption_keyfile": "VERSCHLÜSSELUNG (SCHLÜSSELDATEI):",
        "integrity_operations": "INTEGRITÄTSOPERATIONEN:",
        "vault_operations": "TRESOR-OPERATIONEN:",
        "decryption_viewing": "ENTSCHLÜSSELUNG & ANZEIGE:",
        "language_settings": "SPRACHEINSTELLUNGEN:",
        "workflow_examples": "WORKFLOW-BEISPIELE:",
        "gen_pass_12": "12-stelliges Passwort generieren",
        "gen_key_example": "Verschlüsselungsschlüsseldatei generieren",
        "obfuscate_simple": "Python-Script obfuszieren",
        "encrypt_pass_file": "Datei mit Passwort verschlüsseln",
        "encrypt_key_file": "Datei mit Schlüsseldatei verschlüsseln",
        "encrypt_integrity_pass": "Mit Integritätsprüfung verschlüsseln (Passwort)",
        "encrypt_integrity_key": "Mit Integritätsprüfung verschlüsseln (Schlüsseldatei)",
        "verify_integrity_pass": "Dateiintegrität überprüfen (Passwort)",
        "vault_create_pass": "100MB Tresor mit Passwort erstellen",
        "vault_create_key": "500MB Tresor mit Schlüsseldatei erstellen",
        "vault_list": "Alle Tresore auflisten",
        "vault_info": "Tresor-Informationen anzeigen",
        "vault_add_file": "Datei zum Tresor hinzufügen",
        "vault_list_files": "Dateien im Tresor auflisten",
        "vault_extract_file": "Datei aus Tresor extrahieren",
        "vault_remove_file": "Datei aus Tresor entfernen",
        "vault_delete": "Tresor löschen",
        "vault_move_file": "Datei in Tresor verschieben (Original löschen)",
        "decrypt_edit_pass": "Datei entschlüsseln und bearbeiten (Passwort)",
        "view_only_key": "Nur Dateiinhalt anzeigen (Schlüsseldatei)",
        "decrypt_integrity_pass": "Mit Integritätsprüfung entschlüsseln (Passwort)",
        "change_lang": "Oberflächensprache ändern",
        "workflow_1": "Obfuszierung + Verschlüsselung:",
        "workflow_2": "Sicherer Workflow mit Integrität:",
        "workflow_3": "Passwortbasierter Workflow:",
        "workflow_4": "Tresor-Verwaltungs-Workflow:",
        "vault_created": "Tresor erfolgreich erstellt: {}",
        "vault_deleted": "Tresor erfolgreich gelöscht: {}",
        "vault_not_found": "Tresor nicht gefunden: {}",
        "vault_exists": "Tresor existiert bereits: {}",
        "vault_list_empty": "Keine Tresore gefunden",
        "vault_size_invalid": "Tresorgröße muss zwischen 1MB und 1024MB liegen",
        "vault_help_title": "ObfUtil Vault - Verschlüsselte Dateicontainer",
        "vault_help_usage": "Verwendung: obfutil vault <befehl> [optionen]",
        "vault_help_examples": "BEISPIELE:",

        "status_cmd": "Systemstatus und Gesundheit anzeigen",
        "config_cmd": "Systemkonfiguration verwalten",
        
        "status_example": "Systemstatus und Statistiken anzeigen",
        "config_example": "Systemsprache auf Russisch ändern",
        "config_show_example": "Aktuelle Konfiguration anzeigen",
        "batch_encrypt_example": "Verschlüssele alle .txt Dateien im aktuellen Verzeichnis",
        "batch_decrypt_example": "Entschlüssele alle .enc Dateien im aktuellen Verzeichnis",
        
        "system_operations": "SYSTEMOPERATIONEN:",
        "batch_operations": "STAPELVERARBEITUNG:",
        
        "system_status": "Systemstatus",
        "vaults_count": "Anzahl der Tresore",
        "key_file_status": "Schlüsseldateistatus",
        "logs_size": "Protokollgröße",
        "configuration": "Konfiguration",
        "current_language": "Aktuelle Sprache",
        "encryption_method": "Verschlüsselungsmethode",
        'system_status': 'SYSTEMSTATUS',
        
        "batch_stats_files": "Dateien verarbeitet",
        "batch_stats_successful": "Erfolgreich",
        "batch_stats_failed": "Fehlgeschlagen",
        "batch_stats_total_size": "Gesamtgröße", 
        "batch_stats_processed_size": "Verarbeitete Größe",
        "batch_stats_processing_time": "Verarbeitungszeit",
        "batch_stats_speed": "Durchschnittsgeschwindigkeit",
        "key_size": "Schlüsselgröße",
        "logs_dir": "Protokollverzeichnis",
        "vaults_dir": "Tresorverzeichnis",
        "exists": "Existiert",
        "not_found": "Nicht gefunden",
        "seconds": "Sekunden",

        "vault_analyze": "Tresornutzung analysieren",
        "vault_capacity": "Kapazität",
        "vault_used_space": "Belegter Speicher",
        "vault_free_space": "Freier Speicher",
        "vault_largest_file": "Größte Datei",
        "vault_file_types": "Dateitypen",
        "total_files": "Dateien gesamt",
        "total_size": "Gesamtgröße",
    }
}

def get_translation(language, key):
    if language not in SUPPORTED_LANGUAGES:
        language = "en"  # fallback
    return _locales.get(language, _locales["en"]).get(key, key)